name: Second-Workflow


on:
  workflow_dispatch:

env: 
  variable1 : ${{ vars.variable1 }}
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env: 
      variablejob1: valeurjob1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run script
        run: |
          echo "$variablejob1",
          echo "$variablejob2",
          echo "$variable1"

  job2:
    runs-on: ubuntu-latest
    env: 
      variablejob2: valeurjob2
    steps:
      - uses: actions/checkout@v4
      
      # Runs a set of commands using the runners shell
      - name: Run script
        run: |
          echo "$variablejob1",
          echo "$variablejob2",
          echo "$variable1"
